### ISSUE TITLE
Rasterizer Memory consumption

### ISSUE THREAD

**Issue by francoisruty** [tensorflow/graphics#31]
I know the rasterizer is not official yet but I create an issue in case of.

Before running the rasterizer, I loaded noything in python shell, nvidia-smi gives me this:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
| 38%   44C    P0    36W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Then I run this code:
H, W = 400, 400
vertices = np.array([[[200.0,0,0], [0, 200.0, 0], [0, 0, 200.0]]])
attributes = np.array([[[1.0], [1.0], [0.0]]])
triangles = np.array([[[0, 2, 1]]])
rendered_depth_maps, triangle_ind_maps, bc_maps = rasterizer_rasterize(vertices=vertices, triangles=triangles, image_width=W, image_height=H, name="rasterize")

Then nvidia-smi gives me this:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
| 33%   45C    P2    39W / 180W |   7801MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Just running a basic example eats all the GPU RAM and does not release it

Here is the output when running the example code:

```
>>> H, W = 400, 400
>>> vertices = np.array([[[200.0,0,0], [0, 200.0, 0], [0, 0, 200.0]]])
>>> attributes = np.array([[[1.0], [1.0], [0.0]]])
>>> triangles = np.array([[[0, 2, 1]]])
>>> rendered_depth_maps, triangle_ind_maps, bc_maps = rasterizer_rasterize(vertices=vertices, triangles=triangles, image_width=W, image_height=H, name="rasterize")
2019-07-01 22:19:52.613114: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-01 22:19:52.626202: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-07-01 22:19:52.911914: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1009] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-01 22:19:52.913031: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x592d250 executing computations on platform CUDA. Devices:
2019-07-01 22:19:52.913049: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-07-01 22:19:52.933811: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-07-01 22:19:52.934420: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x5999540 executing computations on platform Host. Devices:
2019-07-01 22:19:52.934457: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-01 22:19:52.934832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.82GiB
2019-07-01 22:19:52.934868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-07-01 22:19:52.934905: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-07-01 22:19:52.935721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-01 22:19:52.935734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-07-01 22:19:52.935744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-07-01 22:19:52.935991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7605 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
>>> 
```

**Comment by francoisruty** [comment]
To give more context, I'm trying some code from tf_mesh_renderer to implement in TFG vertex attributes interpolation, just after rasterization
But this steps needs some memory to manipulate all pixels, and in my case it crashes since running the rasterizer does not leave any free GPU memory for what comes afterward

**Comment by ioga** [comment]
It's a default tensorflow behavior to allocate almost all available GPU memory. It's not specific to this rasterizer. Some more info here: https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth

**Comment by francoisruty** [comment]
@ioga thx for the information, do you know how people proceed then?
Because right after the code block I mentionned I have other tensorflow code that throws an OOM as a consequence
Shouldn't the tensorflow code immediately following the one I posted use that allocated memory instead of trying to allocate new one?
Seems I'm missing something

**Comment by francoisruty** [comment]
for reference, here is the full code (this code aims at computing the vertex attributes interpolated values, it was taken from google tf_mesh_renderer repo:


```
# Test TFG rasterizer with attributes interpolation
H, W = 400, 400
vertices = np.array([[[200.0,0,0], [0, 200.0, 0], [0, 0, 200.0]]])
attributes = np.array([[[1.0], [1.0], [0.0]]])
triangles = np.array([[[0, 2, 1]]])
#TF allocates there all the GPU memory
rendered_depth_maps, triangle_ind_maps, bc_maps = rasterizer_rasterize(vertices=vertices, triangles=triangles, image_width=W, image_height=H, name="rasterize")

batch_size = vertices.shape[0]
vertex_count = vertices.shape[1]

per_image_barycentric_coordinates = []
per_image_vertex_ids = []
for im in range(batch_size): #for each batch
    barycentric_coords = bc_maps[im]
    triangle_ids = triangle_ind_maps[im]
    per_image_barycentric_coordinates.append(
        tf.reshape(barycentric_coords, [-1, 3])) #with tf.reshape we stack all pixels in one huge column
    # Gathers the vertex indices now because the indices don't contain a batch
    # identifier, and reindexes the vertex ids to point to a (batch,vertex_id)
    vertex_ids = tf.gather(triangles, tf.reshape(triangle_ids, [-1])) #with tf.reshape we stack all pixels in one huge column
    reindexed_ids = tf.add(vertex_ids, im * vertex_count)
    reindexed_ids = tf.dtypes.cast(reindexed_ids, tf.int32)
    per_image_vertex_ids.append(reindexed_ids)

barycentric_coordinates = tf.concat(per_image_barycentric_coordinates, axis=0)
vertex_ids = tf.concat(per_image_vertex_ids, axis=0)

# Indexes with each pixel's clip-space triangle's extrema (the pixel's
# 'corner points') ids to get the relevant properties for deferred shading.
flattened_vertex_attributes = tf.reshape(attributes,
                                           [batch_size * vertex_count, -1])
flattened_vertex_attributes = tf.cast(flattened_vertex_attributes, tf.float32)
corner_attributes = tf.gather(flattened_vertex_attributes, vertex_ids)

# Computes the pixel attributes by interpolating the known attributes at the
# corner points of the triangle interpolated with the barycentric coordinates.
#### OOM HERE
weighted_vertex_attributes = tf.multiply(corner_attributes, tf.expand_dims(barycentric_coordinates, axis=2))
summed_attributes = tf.reduce_sum(weighted_vertex_attributes, axis=1)
attribute_images = tf.reshape(summed_attributes,
                                [batch_size, image_height, image_width, -1])

# Barycentric coordinates should approximately sum to one where there is
# rendered geometry, but be exactly zero where there is not.
alphas = tf.clip_by_value(
  tf.reduce_sum(2.0 * barycentric_coordinates, axis=1), 0.0, 1.0)
alphas = tf.reshape(alphas, [batch_size, image_height, image_width, 1])

attributes_with_background = (
      alphas * attribute_images + (1.0 - alphas) * background_value)

```

This returns:

```
>>> # Computes the pixel attributes by interpolating the known attributes at the
... # corner points of the triangle interpolated with the barycentric coordinates.
... weighted_vertex_attributes = tf.multiply(corner_attributes, tf.expand_dims(barycentric_coordinates, axis=2))

2019-07-02 08:30:00.491572: W tensorflow/core/common_runtime/bfc_allocator.cc:288] Allocator (GPU_0_bfc) ran out of memory trying to allocate 286.10GiB.  Current allocation summary follows.
2019-07-02 08:30:00.491696: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (256): 	Total Chunks: 2, Chunks in use: 1. 512B allocated for chunks. 256B in use in bin. 12B client-requested in use in bin.
2019-07-02 08:30:00.491739: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (512): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491775: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2019-07-02 08:30:00.491808: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491840: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491872: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491903: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491935: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.491967: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (65536): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492016: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492068: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492167: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (524288): 	Total Chunks: 3, Chunks in use: 2. 1.83MiB allocated for chunks. 1.22MiB in use in bin. 1.22MiB client-requested in use in bin.
2019-07-02 08:30:00.492236: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (1048576): 	Total Chunks: 4, Chunks in use: 4. 7.32MiB allocated for chunks. 7.32MiB in use in bin. 7.32MiB client-requested in use in bin.
2019-07-02 08:30:00.492302: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (2097152): 	Total Chunks: 2, Chunks in use: 2. 6.10MiB allocated for chunks. 6.10MiB in use in bin. 6.10MiB client-requested in use in bin.
2019-07-02 08:30:00.492366: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (4194304): 	Total Chunks: 1, Chunks in use: 0. 4.88MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492426: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492496: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492558: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492614: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492662: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492719: I tensorflow/core/common_runtime/bfc_allocator.cc:633] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 7.41GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-07-02 08:30:00.492785: I tensorflow/core/common_runtime/bfc_allocator.cc:649] Bin for 286.10GiB was 256.00MiB, Chunk State: 
2019-07-02 08:30:00.492852: I tensorflow/core/common_runtime/bfc_allocator.cc:655]   Size: 7.41GiB | Requested Size: 3.05MiB | in_use: 0, prev:   Size: 1.83MiB | Requested Size: 1.83MiB | in_use: 1
2019-07-02 08:30:00.492905: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Free  at 0x7f1fc2000000 of size 256
2019-07-02 08:30:00.492949: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2000100 of size 1280
2019-07-02 08:30:00.492992: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2000600 of size 1920000
2019-07-02 08:30:00.493035: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc21d5200 of size 1920000
2019-07-02 08:30:00.493069: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Free  at 0x7f1fc23a9e00 of size 5120256
2019-07-02 08:30:00.493112: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc288bf00 of size 3200000
2019-07-02 08:30:00.493155: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2b99300 of size 3200000
2019-07-02 08:30:00.493194: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2ea6700 of size 640000
2019-07-02 08:30:00.493236: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2f42b00 of size 256
2019-07-02 08:30:00.493272: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Free  at 0x7f1fc2f42c00 of size 639744
2019-07-02 08:30:00.493310: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc2fdef00 of size 640000
2019-07-02 08:30:00.493347: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc307b300 of size 1920000
2019-07-02 08:30:00.493391: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Chunk at 0x7f1fc324ff00 of size 1920000
2019-07-02 08:30:00.493464: I tensorflow/core/common_runtime/bfc_allocator.cc:668] Free  at 0x7f1fc3424b00 of size 7954219264
2019-07-02 08:30:00.493508: I tensorflow/core/common_runtime/bfc_allocator.cc:677]      Summary of in-use Chunks by size: 
2019-07-02 08:30:00.493557: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 256 totalling 256B
2019-07-02 08:30:00.493596: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 1280 totalling 1.2KiB
2019-07-02 08:30:00.493625: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 2 Chunks of size 640000 totalling 1.22MiB
2019-07-02 08:30:00.493664: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 4 Chunks of size 1920000 totalling 7.32MiB
2019-07-02 08:30:00.493709: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 2 Chunks of size 3200000 totalling 6.10MiB
2019-07-02 08:30:00.493753: I tensorflow/core/common_runtime/bfc_allocator.cc:684] Sum Total of in-use chunks: 14.65MiB
2019-07-02 08:30:00.493806: I tensorflow/core/common_runtime/bfc_allocator.cc:686] Stats: 
Limit:                  7975341261
InUse:                    15361536
MaxInUse:                 20481536
NumAllocs:                     188
MaxAllocSize:              5760000

2019-07-02 08:30:00.493861: W tensorflow/core/common_runtime/bfc_allocator.cc:292] *___________________________________________________________________________________________________
2019-07-02 08:30:00.493963: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[160000,160000,3,1] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 299, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 6325, in mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[160000,160000,3,1] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]
```

It tries to allocate 286GB anyway so even without the first memory allocation issue it would still probably fail, but I think there is a problem with the code, I don't understand why it needs 286GB

>>> corner_attributes.shape
TensorShape([160000, 1, 3, 1])
>>> 
>>> barycentric_coordinates.shape
TensorShape([160000, 3])
>>> 

It's the multiplication of those 2 that yields the issue

NOTE: the tf_mesh_renderer code is tensorflow but runs on CPU only so it may be the algorithm which is just wrong for GPU execution (needs too much memory)

**Comment by francoisruty** [comment]
Ok so I found another way to compute vertex attributes interpolation which works well (I asked the team if I can submit a PR), and anyway this issue didn't seem related to TFG so I'm closing

**Comment by francoisruty** [comment]
Note: without any additional TF code, I still got an OOM with rasterizer_rasterize when I try it with a "real-world" mesh with dozens of thousands of vertices.
I'll wait for TFG rasterizer official release to create an issue with the mesh attached

**Comment by francoisruty** [comment]
@julienvalentin 
And here is a .zip with Dockerfile to reproduce TFG rasterizer OOM
[test_tfg.zip](https://github.com/tensorflow/graphics/files/3355866/test_tfg.zip)

cd test_tfg
sudo docker build -t test_tfg .
sudo docker run -it --runtime=nvidia test_tfg /bin/bash
python3 script.py

You get an OOM, and the mesh is quite small

**Comment by francoisruty** [comment]
correction, with TF2 beta it eventually finishes after like 12min, but it uses only the CPU, I have no idea why
