### ISSUE TITLE
Error with axis_angle.rotate and @tf.function

### ISSUE THREAD

**Issue by aferrall** [tensorflow/graphics#445]
Hello,

I've been looking into some of the basic transform functionality in tensorflow_graphics, and though I'm able to use it successfully for some initial testing, as soon as it becomes part of a traced graph (via @tf.function decoration), I get errors.

The following is a trivial test case demonstrating what I'm seeing.

```python
import numpy as np
import tensorflow as tf
from tensorflow_graphics.geometry.transformation import axis_angle

@tf.function
def rotate(points, axis, angle):
    return axis_angle.rotate(points, axis, angle)

p = tf.ones((4, 3))
axis = tf.constant([0., 0., 1.])
angle = tf.constant([np.pi / 2])

pT1 = axis_angle.rotate(p, axis, angle)
print(pT1)
pT2 = rotate(p, axis, angle)
print(pT2)
```

In the above pT1 evaluates as expected, but pT2 fails with the following message (during graph construction, as far as I can tell):

```
Traceback (most recent call last):
  File "./bin/tfg_test", line 24, in <module>
    pT2 = rotate(p, axis, angle)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    ./bin/tfg_test:16 rotate  *
        return axis_angle.rotate(points, axis, angle)
    /venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow_graphics/geometry/transformation/axis_angle.py:296 rotate  *
        shape.check_static(
    /venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow_graphics/util/shape.py:206 check_static  *
        if _get_dim(tensor, axis) != value:
    /venvs/venv_tfg/lib64/python3.6/site-packages/tensorflow_graphics/util/shape.py:135 _get_dim  *
        return tensor.shape[axis].value

    AttributeError: 'int' object has no attribute 'value'
```

I haven't verified with other functions, but I expect `axis_angle.rotate` is not alone, as the error appears to originate in shape validation.

Is this a known issue?

Thanks,
-Adam

**Comment by aferrall** [comment]
Looks like this might be fixed in mainline, just not in the currently released code. Sorry for the noise.
